/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#6b38d4",
        "on-primary": "#ffffff",
        "primary-container": "#8455ef",
        "on-primary-container": "#fffbff",
        "secondary": "#a43073",
        "on-secondary": "#ffffff",
        "secondary-container": "#fc79bd",
        "on-secondary-container": "#76014e",
        "tertiary": "#765700",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#956e00",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fef7ff",
        "on-background": "#1d1a23",
        "surface": "#fef7ff",
        "on-surface": "#1d1a23",
        "surface-variant": "#e7e0ed",
        "on-surface-variant": "#494454",
        "outline": "#7b7486",
        "outline-variant": "#cbc3d7",
        "inverse-surface": "#322f39",
        "inverse-on-surface": "#f5eefb",
        "inverse-primary": "#d0bcff",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed": "#23005c",
        "primary-fixed-dim": "#d0bcff",
        "on-primary-fixed-variant": "#5516be",
        "secondary-fixed": "#ffd8e7",
        "on-secondary-fixed": "#3d0026",
        "secondary-fixed-dim": "#ffafd3",
        "on-secondary-fixed-variant": "#85145a",
        "tertiary-fixed": "#ffdf9f",
        "on-tertiary-fixed": "#261a00",
        "tertiary-fixed-dim": "#f9bd22",
        "on-tertiary-fixed-variant": "#5c4300",
        "surface-dim": "#ded7e4",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f1fe",
        "surface-container": "#f3ebf8",
        "surface-container-high": "#ede5f3",
        "surface-container-highest": "#e7e0ed",
      },
      fontFamily: {
        'h1': ['Epilogue', 'sans-serif'],
        'h2': ['Epilogue', 'sans-serif'],
        'h3': ['Epilogue', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'label-bold': ['Lexend', 'sans-serif'],
        'label-caps': ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      animation: {
        'breathe': 'breathe 19s infinite ease-in-out',
        'breathe-478': 'breathe-478 19s infinite cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}
